#!/usr/bin/env python3
"""Claim intake, CID minting, and full record generation for the Randolph
Genealogy Hub.

Implements Phases 2 and 3 of docs/MYKV_SERVICE_DESIGN.md:
  - Phase 2: validates Claims/*.json against schemas/claim.schema.json,
    evaluates corroboration per Claims/README.md's algorithm, and mints a
    new CID for any PENDING:<key> subject whose birth claim has cleared
    the confirmation bar.
  - Phase 3: fully generates an Individuals/ record — Identity, Parentage,
    Marriages (possibly several), Children (via reverse parent_child
    lookup), Migration Timeline, Military Record, Occupation, and Source
    Citations — from every confirmed claim type about a subject, not just
    birth+parent_child. This only ever applies to "claim-managed" records:
    a subject just minted this run, or one whose existing Individuals/
    file already carries GENERATED_MARKER. A subject's existing,
    hand-authored file (no marker, predates the Claims pipeline) is never
    overwritten, even if claims about it are confirmed — see
    generate_record_content()'s docstring.

Usage:
  python3 tools/cid_registrar.py          # check only; exit 1 on any problem
  python3 tools/cid_registrar.py --write  # also mint/regenerate as needed
"""
import json
import re
import sys
import pathlib
from collections import defaultdict

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import validate_ledger  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
CLAIMS_DIR = ROOT / "Claims"
INDIVIDUALS = ROOT / "Individuals"

EVIDENCE_RANK = {"A": 0, "B": 1, "C": 2, "D": 3}
CONFIRM_THRESHOLD = {"A": 1, "B": 2, "C": 3, "D": None}
VALID_CLAIM_TYPES = {
    "birth", "parent_child", "death", "marriage", "burial",
    "migration", "military", "occupation",
}
VALID_STATUSES = {"pending", "confirmed", "contested", "rejected"}
CID_RE = re.compile(r"^[A-Z]{2,4}-(?:c\d{3,4}|\d{3,4})-[A-Za-z0-9.]+-[A-Z]{2}$")
PENDING_RE = re.compile(r"^PENDING:[a-z0-9][a-z0-9-]*$")
CLAIM_ID_RE = re.compile(r"^CLM-[a-z0-9-]+$")

GENERATED_MARKER = (
    "<!-- GENERATED BY tools/cid_registrar.py from Claims/ — "
    "do not hand-edit; edits here will be overwritten. -->"
)


def load_claims(claims_dir=None):
    if claims_dir is None:
        claims_dir = CLAIMS_DIR
    claims = []
    errors = []
    seen_ids = {}
    for f in sorted(claims_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except Exception as exc:
            errors.append(f"{f.relative_to(ROOT)}: invalid JSON: {exc}")
            continue
        file_errors = validate_claim(data, f)
        if file_errors:
            errors.extend(file_errors)
            continue
        cid_id = data["claim_id"]
        if cid_id in seen_ids:
            errors.append(
                f"{f.relative_to(ROOT)}: duplicate claim_id '{cid_id}' "
                f"(already used by {seen_ids[cid_id].relative_to(ROOT)})"
            )
            continue
        seen_ids[cid_id] = f
        data["_file"] = f
        claims.append(data)
    return claims, errors


def validate_claim(data, f):
    errors = []
    required = ["claim_id", "claim_type", "subject_cid", "assertion", "source", "submitted_by", "submitted_at", "status"]
    for field in required:
        if field not in data:
            errors.append(f"{f.relative_to(ROOT)}: missing required field '{field}'")
    if errors:
        return errors

    if not CLAIM_ID_RE.match(data["claim_id"]):
        errors.append(f"{f.relative_to(ROOT)}: claim_id '{data['claim_id']}' must match ^CLM-[a-z0-9-]+$")
    if data["claim_type"] not in VALID_CLAIM_TYPES:
        errors.append(f"{f.relative_to(ROOT)}: invalid claim_type '{data['claim_type']}'")
    subj = data["subject_cid"]
    if not (CID_RE.match(subj) or PENDING_RE.match(subj)):
        errors.append(f"{f.relative_to(ROOT)}: subject_cid '{subj}' is neither a valid CID nor a PENDING:<key>")
    obj = data.get("object_cid")
    if obj is not None and not (CID_RE.match(obj) or obj == "UNK"):
        errors.append(f"{f.relative_to(ROOT)}: object_cid '{obj}' must be a real CID or 'UNK'")
    source = data.get("source", {})
    if not isinstance(source, dict) or source.get("evidence_level") not in EVIDENCE_RANK:
        errors.append(f"{f.relative_to(ROOT)}: source.evidence_level must be one of A/B/C/D")
    if data["status"] not in VALID_STATUSES:
        errors.append(f"{f.relative_to(ROOT)}: invalid status '{data['status']}'")
    if not isinstance(data.get("assertion"), dict):
        errors.append(f"{f.relative_to(ROOT)}: assertion must be an object")
    return errors


def check_reference_integrity(claims, known_cids):
    errors = []
    for c in claims:
        subj = c["subject_cid"]
        if CID_RE.match(subj) and subj not in known_cids:
            errors.append(f"{c['_file'].relative_to(ROOT)}: subject_cid '{subj}' is not a registered CID")
        obj = c.get("object_cid")
        if obj and CID_RE.match(obj) and obj not in known_cids:
            errors.append(f"{c['_file'].relative_to(ROOT)}: object_cid '{obj}' is not a registered CID")
    return errors


def check_birth_namespaces(claims, registered_namespaces):
    """A birth claim proposing a namespace nobody registered in
    NAMESPACES.md should fail loudly now, not leave the claim silently
    stuck pending forever because mintable_for_pending quietly declines
    to mint into it."""
    errors = []
    for c in claims:
        if c["claim_type"] != "birth":
            continue
        ns = c["assertion"].get("namespace")
        if ns and ns not in registered_namespaces:
            errors.append(
                f"{c['_file'].relative_to(ROOT)}: proposes namespace '{ns}', which isn't "
                f"registered in NAMESPACES.md — register it there first or use a registered namespace"
            )
    return errors


def cluster_key(claim):
    return json.dumps(claim["assertion"], sort_keys=True)


def evaluate(claims):
    """Group by (subject_cid, claim_type); cluster by identical assertion;
    decide confirmed/contested per cluster. Returns dict keyed by
    (subject_cid, claim_type) -> {"clusters": [...], "contested": bool}."""
    groups = defaultdict(list)
    for c in claims:
        groups[(c["subject_cid"], c["claim_type"])].append(c)

    reports = {}
    for key, group_claims in groups.items():
        clusters_map = defaultdict(list)
        for c in group_claims:
            clusters_map[cluster_key(c)].append(c)

        cluster_reports = []
        for cluster_claims in clusters_map.values():
            submitters = {c["submitted_by"] for c in cluster_claims}
            best_level = min(
                (c["source"]["evidence_level"] for c in cluster_claims),
                key=lambda lvl: EVIDENCE_RANK[lvl],
            )
            threshold = CONFIRM_THRESHOLD[best_level]
            confirmed = threshold is not None and len(submitters) >= threshold
            cluster_reports.append({
                "claims": cluster_claims,
                "submitters": submitters,
                "best_level": best_level,
                "confirmed": confirmed,
            })

        reports[key] = {
            "clusters": cluster_reports,
            "contested": len(clusters_map) > 1,
        }
    return reports


def pending_keys(claims):
    keys = set()
    for c in claims:
        if PENDING_RE.match(c["subject_cid"]):
            keys.add(c["subject_cid"])
        obj = c.get("object_cid")
        if obj and PENDING_RE.match(obj):
            keys.add(obj)
    return keys


def next_sequence(known_cids, ns, year, state):
    pattern = re.compile(rf"^{re.escape(ns)}-c?{year}-(\d+)-{re.escape(state)}$")
    seqs = [int(m.group(1)) for cid in known_cids if (m := pattern.match(cid))]
    return max(seqs, default=0) + 1


def mintable_for_pending(pending_key, reports, claims, known_cids):
    """Return (new_cid, birth_claims, parent_claims) if pending_key's birth
    claim is confirmed & uncontested & structurally complete; else None."""
    birth_report = reports.get((pending_key, "birth"))
    if not birth_report or birth_report["contested"]:
        return None
    confirmed = [r for r in birth_report["clusters"] if r["confirmed"]]
    if len(confirmed) != 1:
        return None
    birth_claims = confirmed[0]["claims"]
    assertion = birth_claims[0]["assertion"]
    ns = assertion.get("namespace")
    year = assertion.get("birth_year")
    state = assertion.get("birth_state")
    name = assertion.get("full_legal_name")
    if not (ns and year and state and name):
        return None

    seq = next_sequence(known_cids, ns, year, state)
    new_cid = f"{ns}-{year}-{seq:03d}-{state}"

    parent_report = reports.get((pending_key, "parent_child"), {"clusters": [], "contested": False})
    parent_claims = []
    if not parent_report["contested"]:
        for cluster in parent_report["clusters"]:
            if cluster["confirmed"]:
                parent_claims.append(cluster["claims"][0])

    return new_cid, birth_claims, parent_claims


def confirmed_claims_for(cid, claim_type, reports):
    """All claims from confirmed, uncontested clusters for (cid, claim_type)."""
    report = reports.get((cid, claim_type))
    if not report or report["contested"]:
        return []
    out = []
    for cluster in report["clusters"]:
        if cluster["confirmed"]:
            out.extend(cluster["claims"])
    return out


def children_of(cid, all_claims, reports):
    """Subjects whose confirmed, uncontested parent_child claim names `cid`
    as object_cid — i.e. this subject's children, found by scanning every
    other subject's own confirmed parentage claims rather than anything
    stored on `cid` itself."""
    children = set()
    for c in all_claims:
        if c["claim_type"] != "parent_child" or c.get("object_cid") != cid:
            continue
        confirmed = confirmed_claims_for(c["subject_cid"], "parent_child", reports)
        if c in confirmed:
            children.add(c["subject_cid"])
    return sorted(children)


def is_generated(path):
    return path.exists() and GENERATED_MARKER in path.read_text(encoding="utf-8")


def existing_path_for(cid):
    matches = list(INDIVIDUALS.glob(f"{cid}__*.md"))
    return matches[0] if matches else None


def generate_record_content(cid, all_claims, reports):
    """Build the full Individuals/ file content for `cid` from every
    confirmed claim type about it, plus its confirmed children (found via
    other subjects' parent_child claims). Returns (filename, content), or
    None if `cid` has no confirmed birth claim of its own — a record can
    only be claim-generated from an identity claim, never inferred purely
    from claims about its relationships. This is also why an existing,
    hand-authored record (no confirmed birth claim behind it, since it
    predates the Claims pipeline) is never a candidate for regeneration:
    the caller only calls this for CIDs already known to be claim-managed
    (freshly minted, or already carrying GENERATED_MARKER)."""
    birth_claims = confirmed_claims_for(cid, "birth", reports)
    if not birth_claims:
        return None
    birth = birth_claims[0]
    name = birth["assertion"]["full_legal_name"]

    parent_claims = confirmed_claims_for(cid, "parent_child", reports)
    father_cid = mother_cid = "UNK"
    for c in parent_claims:
        rel = c["assertion"].get("relationship")
        parent = c.get("object_cid", "UNK")
        if rel == "father":
            father_cid = parent
        elif rel == "mother":
            mother_cid = parent
    parentage_level = parent_claims[0]["source"]["evidence_level"] if parent_claims else birth["source"]["evidence_level"]

    death_claims = confirmed_claims_for(cid, "death", reports)
    death = "UNK"
    if death_claims:
        d = death_claims[0]["assertion"]
        parts = [p for p in (d.get("death_date"), d.get("death_place")) if p]
        death = ", ".join(parts) if parts else "UNK"

    burial_claims = confirmed_claims_for(cid, "burial", reports)
    burial = burial_claims[0]["assertion"].get("burial_place", "UNK") if burial_claims else "UNK"

    marriage_claims = confirmed_claims_for(cid, "marriage", reports)
    marriage_blocks = []
    for c in marriage_claims:
        a = c["assertion"]
        marriage_blocks.append(
            f'Spouse_CID: {c.get("object_cid", "UNK")}  \n'
            f'Marriage_Date: {a.get("marriage_date", "UNK")}  \n'
            f'Marriage_Location: {a.get("marriage_place", "UNK")}  \n'
            f'Source_ID: {c["source"].get("source_id", "UNK")}  '
        )
    if not marriage_blocks:
        marriage_blocks = ["Spouse_CID: UNK  \nMarriage_Date: UNK  \nMarriage_Location: UNK  \nSource_ID: UNK  "]

    children = children_of(cid, all_claims, reports)
    children_lines = [f"- {c}" for c in children] if children else ["- UNK (Pending discovery)"]

    migration_claims = confirmed_claims_for(cid, "migration", reports)
    migration_lines = []
    for c in migration_claims:
        a = c["assertion"]
        migration_lines.append(
            f'Year: {a.get("year", "UNK")}  \n'
            f'Location: {a["location"]}  \n'
            f'Source_ID: {c["source"].get("source_id", "UNK")}  '
        )
    migration_text = "\n\n".join(migration_lines) if migration_lines else "Year: UNK  \nLocation: UNK  \nSource_ID: UNK  "

    military_claims = confirmed_claims_for(cid, "military", reports)
    if military_claims:
        m = military_claims[0]["assertion"]
        military_text = (
            f'Unit: {m.get("unit", "")}  \n'
            f'Rank: {m.get("rank", "")}  \n'
            f'Service_Dates: {m.get("service_dates", "")}  \n'
            f'Source_ID: {military_claims[0]["source"].get("source_id", "UNK")}  '
        )
    else:
        military_text = "Unit:  \nRank:  \nService_Dates:  \nSource_ID:  "

    occupation_claims = confirmed_claims_for(cid, "occupation", reports)
    occupation_text = occupation_claims[0]["assertion"].get("description", "UNK") if occupation_claims else "UNK"

    all_source_claims = (
        birth_claims + parent_claims + death_claims + burial_claims
        + marriage_claims + migration_claims + military_claims + occupation_claims
    )
    seen_sources = set()
    source_lines = []
    for c in all_source_claims:
        src = c["source"]
        key = (src.get("source_id", "UNK"), src["description"])
        if key in seen_sources:
            continue
        seen_sources.add(key)
        source_lines.append(
            f'Source_ID: {src.get("source_id", "UNK")}  \n'
            f'Description: {src["description"]}  \n'
            f'Evidence_Level: {src["evidence_level"]}  '
        )

    filename_name = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")

    content = f"""{GENERATED_MARKER}

# Identity

Canonical_ID: {cid}
Full_Legal_Name: {name}
Known_As:
Birth: {birth["assertion"].get("birth_date", str(birth["assertion"]["birth_year"]))}, {birth["assertion"].get("birth_place", birth["assertion"]["birth_state"])}
Death: {death}
Burial: {burial}
Primary_Locations:
- {birth["assertion"]["birth_state"]}

Notes: Generated by tools/cid_registrar.py from confirmed Claims/ submissions. See Claims/{birth["claim_id"]}.json and related claims for full submission detail.

---

# Parentage

Father_CID: {father_cid}
Mother_CID: {mother_cid}
Evidence_Level: {parentage_level}

---

# Marriages

{chr(10).join(marriage_blocks)}

---

# Children

Child_CID:
{chr(10).join(children_lines)}

---

# Migration Timeline

{migration_text}

---

# Military Record

{military_text}

---

# Occupation

{occupation_text}

---

# Source Citations

{chr(10).join(source_lines)}

---

# Evidence Confidence Rating

{birth["source"]["evidence_level"]}
"""
    return f"{cid}__{filename_name}.md", content


def write_record(cid, all_claims, reports):
    """Generate and write cid's record. Returns the path written, or None
    if cid isn't claim-managed (no confirmed birth claim of its own)."""
    result = generate_record_content(cid, all_claims, reports)
    if result is None:
        return None
    filename, content = result
    old_path = existing_path_for(cid)
    if old_path and old_path.name != filename:
        old_path.unlink()
    path = INDIVIDUALS / filename
    path.write_text(content, encoding="utf-8")
    return path


def rewrite_pending_refs(claims, pending_key, new_cid):
    for c in claims:
        changed = False
        if c["subject_cid"] == pending_key:
            c["subject_cid"] = new_cid
            changed = True
        if c.get("object_cid") == pending_key:
            c["object_cid"] = new_cid
            changed = True
        if changed:
            f = c["_file"]
            out = {k: v for k, v in c.items() if k != "_file"}
            f.write_text(json.dumps(out, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def main():
    write = "--write" in sys.argv
    errors = []

    known_records, ledger_errors = validate_ledger.load_individuals()
    errors.extend(ledger_errors)
    known_cids = set(known_records)

    claims, claim_errors = load_claims()
    errors.extend(claim_errors)
    errors.extend(check_reference_integrity(claims, known_cids))

    registered_namespaces, namespace_errors = validate_ledger.load_registered_namespaces()
    errors.extend(namespace_errors)
    if registered_namespaces is not None:
        errors.extend(check_birth_namespaces(claims, registered_namespaces))

    if errors:
        print("CID REGISTRAR FAILED")
        for e in errors:
            print("-", e)
        sys.exit(1)

    if not claims:
        print("CID REGISTRAR PASSED (0 claims)")
        return

    generated_cids_before = {
        cid for cid, rec in known_records.items() if is_generated(rec["file"])
    }

    # Phase 2: mint a CID for every currently-confirmed, structurally-complete
    # PENDING:<key> birth claim, rewriting that key to the real CID everywhere
    # it's used so later claims about the same person resolve normally.
    pending = []  # human-readable "not yet applied" messages, check-mode only
    minted = []
    already_reported = set()
    remaining_claims = claims
    for _ in range(len(pending_keys(claims)) + 1):
        reports = evaluate(remaining_claims)
        ready = None
        for key in sorted(pending_keys(remaining_claims)):
            if key in already_reported:
                continue
            result = mintable_for_pending(key, reports, remaining_claims, known_cids)
            if result:
                ready = (key, result)
                break
        if not ready:
            break
        key, (new_cid, birth_claims, parent_claims) = ready
        already_reported.add(key)
        if write:
            rewrite_pending_refs(remaining_claims, key, new_cid)
        else:
            pending.append(f"{key} is confirmed and mintable as {new_cid} but not yet minted")
        minted.append((key, new_cid))
        known_cids.add(new_cid)

    # Phase 3: (re)generate the full record for every claim-managed CID —
    # freshly minted above, or already carrying GENERATED_MARKER — from
    # every confirmed claim type now on file. Hand-authored records (no
    # marker) are never touched, whatever claims exist about them.
    claim_managed_cids = generated_cids_before | {cid for _, cid in minted}
    reports = evaluate(remaining_claims)
    for cid in sorted(claim_managed_cids):
        result = generate_record_content(cid, remaining_claims, reports)
        if result is None:
            continue  # birth claim no longer confirmed; leave last-known-good file alone
        filename, content = result
        old_path = existing_path_for(cid) if cid in generated_cids_before else None
        current = old_path.read_text(encoding="utf-8") if old_path else None
        if current == content and old_path and old_path.name == filename:
            continue
        if write:
            path = write_record(cid, remaining_claims, reports)
            verb = "Updated" if cid in generated_cids_before else "Minted"
            print(f"{verb} {cid} -> {path.relative_to(ROOT)}")
        else:
            verb = "an update to" if cid in generated_cids_before else "a new record from"
            pending.append(f"{cid} needs {verb} its confirmed claims")

    if pending and not write:
        print("CID REGISTRAR FAILED")
        for p in pending:
            print(f"- {p} — run `python3 tools/cid_registrar.py --write` and commit the result")
        sys.exit(1)

    if write and (minted or claim_managed_cids):
        records, _ = validate_ledger.load_individuals()
        new_text, marker_error = validate_ledger.rewrite_index(records)
        if marker_error:
            print("-", marker_error)
            sys.exit(1)
        validate_ledger.INDEX_FILE.write_text(new_text, encoding="utf-8")
        print(f"Rewrote {validate_ledger.INDEX_FILE.relative_to(ROOT)}")

    print(
        f"CID REGISTRAR PASSED ({len(claims)} claims, {len(minted)} newly minted, "
        f"{len(claim_managed_cids)} claim-managed records)"
    )


if __name__ == "__main__":
    main()
